CREATE TABLE `your_project_id.your_dataset_id.employees` (
    EMPLOYEE_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE_NUMBER STRING,
    HIRE_DATE STRING,
    JOB_ID STRING,
    SALARY NUMERIC,
    COMMISSION_PCT NUMERIC,
    MANAGER_ID STRING,
    DEPARTMENT_ID STRING
);